server {

    listen 80;

    server_name localhost twojadomena.pl www.twojadomena.pl;

    root /usr/share/nginx/html;
    index index.html;

    #
    # Certbot
    #
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    #
    # React
    #
    location / {
        try_files $uri $uri/ /index.html;
    }

    #
    # Cache dla statycznych plików
    #
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

}